### ISSUE TITLE
🏃omnibox⌨

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#274]
- [x]  Support `🏃omnibox⌨`  [API](https://developer.chrome.com/extensions/omnibox) ?

**Some extensions of only omnibox search:**

- Instant Multi Search 　　🏃omnibox⌨`m`  　(This is more direct and easy to use)
　　https://chrome.google.com/webstore/detail/aamgapdgopfdmokckpkfciiddpahbbcg
- Custom Search Engine  　　🏃omnibox⌨`ms`  (Same purpose as 👆, but need to remember the special syntax, which is relatively complicated.)
　　https://chrome.google.com/webstore/detail/kelahdmegihhooaelnaahkeggodajdjf

<details>
<summary>Details</summary>

`chrome://settings/searchEngines#:~:text=added by extensions`
`chrome://flags/#omnibox-ui-max-autocomplete-matches`

**Some other omnibox extensions  :**
- Omnibox Timer Again  　　🏃omnibox⌨`ta`
　　https://chrome.google.com/webstore/detail/nocmdcegkncmgdianofhdlhbaoinmonm
- Bookmark Search  　　🏃omnibox⌨`bm`
　　https://chrome.google.com/webstore/detail/hhmokalkpaiacdofbcddkogifepbaijk

![209_01142615](https://user-images.githubusercontent.com/10995302/91808721-2f6de180-ec5f-11ea-9f81-d863d143956f.png)
`key` is the usage of 🏃omnibox⌨key
`CS` is already very powerful, but it would be better if can also support 🏃omnibox⌨

## 🎬Gif demo👇
![209_04133717](https://user-images.githubusercontent.com/10995302/92203449-c632dc00-eeb3-11ea-9028-a41c62555550.png) use `Instant Multi Search` to demo

![omnibox](https://user-images.githubusercontent.com/10995302/88993556-e30a4b80-d318-11ea-8b5a-70794067eeaa.gif)

</details>

----

<details>
<summary><s> Done: </summary>

`sidebar` only auto open on the Search Results
![209_12012124](https://user-images.githubusercontent.com/10995302/92954614-4cdc5000-f496-11ea-8af4-1c306a93f049.png)

### In other words,  can achieve 👇: 
　　on the **normal** page , do not open  `sidebar`  by default, 
　　but `sidebar` only auto open on the Search Results.

</s>

</details>

<details>
<summary><s> Done:   	</summary>

 support the `Mouse-Middle`
![209_01113156](https://user-images.githubusercontent.com/10995302/91791858-c5e1d900-ec46-11ea-934f-53940482a523.png) talking about 🎡 being pressed instead of being scrolled.

`chrome-extension://ddippghibegbgpjcaaijbacfhjjeafjh/options.html#:~:text=Select text and open using a mouse button`
## 👆 Added: support 🎡.  👇
![209_01114644](https://user-images.githubusercontent.com/10995302/91792757-df842000-ec48-11ea-8ca5-fa81f7e65c75.png)

Because, when the text is selected, using the `left/right button`, it is more or less disturbing.
But `🎡 selection` has no other purpose at this time, so it is actually very convenient to trigger some functions,  Use 🎡 to trigger, there are almost no other side effects or conflicts with other functions.
So, if can add 🎡, will be perfect.

![209_01111542](https://user-images.githubusercontent.com/10995302/91790949-7ef2e400-ec44-11ea-945a-3d58128a0f06.png)
</s>
</details>

**Comment by ssborbis** [comment]
> 1. Can support the Mouse-Middle🎡 ❓

Works fine with Click but Hold is sketchy because the scroll tool opens on mousedown (in FF at least) so you'd get the icon every time. I'll enable it though.

> 2. Can support the 🏃omnibox⌨ ❓

I've never once used the omnibox so I'll need to spend some time exploring it before doing anything

> 3. ☑Open the sidebar automatically when on the Search Results ❓

Not sure I follow. You want an option to open the fixed-positioned search engine menu (sidebar) on a search results page? What's your workflow like for this to be useful?

**Comment by dnknn** [comment]
Thank you for the reply. sorry for my English🤦, That's great you can understand the meaning.

> Works fine with Click but Hold is sketchy .... in FF

🎡 with `Click` It's enough and right.  
🎡 with `Hold` is  almost meaningless.  also I have not used 🦊Firefox.

---

> I've never once used the omnibox ...

It doesn't matter, omnibox is very simple and easy to use.The omnibox usage provided by `Chrome` itself 👇
`chrome://settings/searchEngines
`![209_01162329](https://user-images.githubusercontent.com/10995302/91825928-7cf24a80-ec6f-11ea-8d24-712101e74dc3.png)
![209_01162512](https://user-images.githubusercontent.com/10995302/91826112-b88d1480-ec6f-11ea-8aba-2bbf916a447d.png) Basic usage: 🏃omnibox⌨key+Tab/Space

❶ `Alt+D` to focus Address Bar  　❷ Typing   `b`　❸Press `Tab` or `Space` ❹enjoy.

<details>
<summary>Details</summary>

Hidden advanced usage for add `javascript:`(`Bookmarklet`) code , then it is use 🏃omnibox⌨+`Enter`.

</details>


If you want to experience the expansion of omnibox, I have already given 4 examples above.
Among them, [Instant Multi Search](https://chrome.google.com/webstore/detail/aamgapdgopfdmokckpkfciiddpahbbcg), I want to tell you how to use it.
![209_01163504](https://user-images.githubusercontent.com/10995302/91827197-1b32e000-ec71-11ea-95dc-ea8a0f6f9fb8.png)
![209_01164034](https://user-images.githubusercontent.com/10995302/91827769-de1b1d80-ec71-11ea-9060-430b8752301f.png)
⚠ ❶ `Alt+D`   ➩`m`  ➩`Tab` or `Space` to  call this extension, then flexible usage within itself👇 
　　❷Typing `s`    ❸continue press `Space`  (Blank character) ❻can call the `s` folder to enjoy.


---


> You want an option to open the fixed-positioned search engine menu (sidebar) on a search results page? 

Because it can be realized that it is not displayed by default pages, but automatic displayed on the pages of search results.The purpose is to facilitate jump to other search results page,
For example, when you are not satisfied with this search results page, it will allow you to easily jump to other engines again.

## Let me add one more point: 
If you want to adopt this suggestion, you can also add URL list management that automatically appears sidebar in the future (If it is easy to implement.)
For example:  `https://google.com/search?*q=*` (wildcard)  or `^https://google\.com/search\?.*q=.*` (RegExp)
Then when this page is matched, the sidebar will automatically appear.

Of course, about the automation of the sidebar, now it is just a discussion to let you know. As for whether it is necessary, you can decide for yourself🙂


> What's your workflow like for this to be useful?

I have used many other multiple search extensions,
But your extension is new to me, and I intend to be the main extension, because it has many functions and is very powerful.

**Comment by dnknn** [comment]
![209_01181545](https://user-images.githubusercontent.com/10995302/91837939-4e7c6b80-ec7f-11ea-90fb-1e4d7b32caa8.png)

👆 You can also increase the behavior of mouse events to trigger the `Sidebar`

**Comment by ssborbis** [comment]
I've added Middle button click to the repo for testing

Things are a bit busy lately, but I'll get to the other suggestions when I have time.

**Comment by dnknn** [comment]
Don't worry at all, take your time if  have time.

**Comment by dnknn** [comment]
@ssborbis  
I re-edited/updated the `sidebar auto-appear on the Search Results, but not the normal page` ,
Now it is very clear, very easy to understand what it mean.

<details>
<summary>👁 click to look at this picture , says it all</summary>

![209_04141250](https://user-images.githubusercontent.com/10995302/92205750-e913bf00-eeb8-11ea-93e4-85c57f042ab3.png)

</details>

**Comment by ssborbis** [comment]
Adding the option to open the sidebar on results pages should be relatively easy.

Out of curiosity, are you displaying the sidebar as a floating window or a docked panel (double-click the move bar)?

**Comment by dnknn** [comment]
> displaying the sidebar as a floating window or a docked panel (double-click the move bar)?

I do not understand what you said, but I think it should be at least  that #277

**Comment by dnknn** [comment]
Hi @ssborbis ! I specially downloaded the 🆕 repo to test, then found:

☑ `sideBar.openOnResults` , but  `sidebar` do not auto open on the Search Results page.

![209_12013847](https://user-images.githubusercontent.com/10995302/92955993-b6f5f480-f498-11ea-87bf-f24b908ceea9.png)

![1111](https://user-images.githubusercontent.com/10995302/92956406-6763f880-f499-11ea-8033-220e7429b0ae.gif)

**Comment by ssborbis** [comment]
Hmm... I'll check chrome. It's working for me in FF

**Comment by ssborbis** [comment]
Ah, I put the code after highlighting. I'll rearrange. For testing, try enabling highlighting.

![Untitled](https://user-images.githubusercontent.com/24310997/92963821-af9efe80-f438-11ea-9f5d-3a11e7249b67.png)

**Comment by ssborbis** [comment]
I also updated the repo if you want to try without highlighting

**Comment by dnknn** [comment]
👍 I tested it and it works great💪.  but I finally made a suggestion @ssborbis 


![209_12043257](https://user-images.githubusercontent.com/10995302/92970315-0cd69680-f4b1-11ea-84b8-edc461767f77.png)

##  Can you add 🔍icon to the \<Sidebar\> itself for convenient switching?

>  ⚠ It has nothing to do with the options of `/options.html#sidebar`

---
Expected behavior: can switch any case.

## 　　 　　 　　 　　❓ How to achieve: 📜
- 	## ❶ 👁seeing 👇
![209_12050932](https://user-images.githubusercontent.com/10995302/92973168-2af2c580-f4b6-11ea-92e2-ad6529eeee27.png)

In addition to the `left-click` drag and `double-click` dock window in that area, it can now also be used to switch to a 🔍 icon with the `middle-button`.


- 	## ❷ 👁seeing 👇
![209_12045223](https://user-images.githubusercontent.com/10995302/92971874-d8b0a500-f4b3-11ea-8557-42c2462b5b48.png)


- 	❷ Can use `Esc` to switch when it receives focus (This must be as an ⚙ (ON/OFF))


-----
### ⚠Final supplementary note:  　remember switch state .

When ☑`sideBar.openOnResults` , then  it also remember switch state on the Search Results pages, 
or can be set separately.

**Comment by ssborbis** [comment]
> Can you add 🔍icon to the <Sidebar> itself for convenient switching?

![minimize](https://user-images.githubusercontent.com/24310997/92988131-7db88700-f48e-11ea-93fa-d733e3cab00f.gif)

**Comment by dnknn** [comment]
@ssborbis very beautiful. Yes, this terminology is called `minimize` , very correct!

<details>
<summary>Details</summary>

> ![minimize](https://user-images.githubusercontent.com/24310997/92988131-7db88700-f48e-11ea-93fa-d733e3cab00f.gif)

</details>

It would be perfect if it can support the following 2 situations, If easy to achieve.

❶ `/options.html#advanced`  add 👉 ⬜ `sideBar.openOnResultsMinimizeBydefaultAlways`
> 　　　　 sideBar.openOnResults `&&` Minimize By default always
>  　　　   👆 It is an independent switch for search results pages only, so 👇

❷ `/options.html#advanced`  remove  `sideBar.rememberState` , then change to 👇

![209_12173040](https://user-images.githubusercontent.com/10995302/92992457-b2275400-f51d-11ea-9201-d04c4273d72f.png)


if only ☑ `Remember minimize state`, it also can like this :
![1111](https://user-images.githubusercontent.com/10995302/92992182-af2b6400-f51b-11ea-8d66-636969a7d22f.gif)

⚠ `/options.html#sidebar#Open the Sidebar any time using a hotkey` certainly cannot be minimized by default.

----

### Do you think this change would be better?

> Because it can realize the independent ON/OFF `sideBar.openOnResultsMinimizeBydefaultAlways` on the search results page, or normal pages can also `Remember minimize state`.

**Comment by ssborbis** [comment]
I'm still thinking on how to implement this. I may not get to it before the next release.

**Comment by dnknn** [comment]
> I'm still thinking on how to implement this. I may not get to it before the next release.

Thank you, but it's okay. If it's not easy to implement, just ignore it. After all, I also feel a bit logically confused.

But you can add an `sideBar.openOnResults.Minimize` advanced option of `ON`/`OFF` 
![2010_05163620](https://user-images.githubusercontent.com/10995302/95057562-efe85880-0728-11eb-8ba9-917c3d2e9667.png)

👆 This option is higher than the logic of other methods, highest priority. No matter what else, once this option is ☑, it will take effect 100% in the search results.

purpose:  Automatically open the sideBar in the search results, but do not want it to be automatically expanded, In other words, it is automatically minimized(🔍 icon) in the search results.

**Comment by ssborbis** [comment]
> But you can add an sideBar.openOnResults.Minimize advanced option of ON/OFF

You got it.

**Comment by dnknn** [comment]
If you don't want to support the omnibox function, you can close this issue.
Thanks♪!

**Comment by ssborbis** [comment]
I'll get there. I'm wanting to get a new release out with the current changes before adding any new features.

**Comment by dnknn** [comment]
> I'll get there. I'm wanting to get a new release out with the current changes before adding any new features.

well, The update has changed a lot of content, and it is indeed time to release a new version to all users. It is also good to check the stability and performance..

**Comment by ssborbis** [comment]
v1.27 live on AMO. ChromeStore in a day or 2

**Comment by dnknn** [comment]
ok, Thanks

**Comment by ssborbis** [comment]
I've started adding omnibox support to the repo

Right now, the keyword is cs

Format is `cs HOTKEYS SEARCHTERMS`

`HOTKEYS` can be a list of valid hotkeys, no separator ie `cs bdg firefox` will open background tabs to searches in Bing, DuckDuckGo, and Google for me, as I have those hotkeys (b,d,g) set to those engines respectively.

I'm still unsure of what to display in the suggestions list. Maybe you have some thoughts.

**Comment by dnknn** [comment]
👍Excellent, I tested it and felt okay!

> I'm still unsure of what to display in the suggestions list

I don't quite understand what you mean?

I have better suggestions:
- Do we want to set a separate omnibox-hotkeys column for omnibox instead of sharing it with page-hotkeys.
![image](https://user-images.githubusercontent.com/10995302/99931602-1d986800-2d90-11eb-95b7-4ef71a7f5af1.png)
Because for omnibox, no matter how many hotkeys you set, it will not cause misoperation, for page hotkey, if there are too many settings, it may have a negative effect, Therefore, the user can set separate hotkeys.
	

- Support default, i.e. open without hotkeys ( e.g. `cs SEARCHTERMS` ), just follow to open as the search engine used last time,

- Support hotkey of folders.
Why `omnibox` can't  support hotkey for folders?  e.g. `cs a SEARCHTERMS`
![image](https://user-images.githubusercontent.com/10995302/99931023-0bb5c580-2d8e-11eb-878f-c6ef1b223361.png)


Have you tested the omnibox feature of this [Instant Multi Search](https://chrome.google.com/webstore/detail/aamgapdgopfdmokckpkfciiddpahbbcg) extension?

**Comment by ssborbis** [comment]
> Do we want to set a separate omnibox-hotkeys column for omnibox instead of sharing it with page-hotkeys.

I see how there could be a conflict there, but I'm not sure I want to add another field. I'll think on it.

> Support default, i.e. open without hotkeys ( e.g. cs SEARCHTERMS ), just follow to open as the search engine used last time,

> Support hotkey of folders.
Why omnibox can't support hotkey for folders? e.g. cs a SEARCHTERMS

Both should be working now in the latest push

**Comment by ssborbis** [comment]
It's been a while, but I've added a `keyword` field to the search engines manager, adjacent to the hotkey field, for use with the omnibox. The code will look for a single engine with a matching `keyword`. Failing that, it will assume each character is a `hotkey` and search all engines with a matching `hotkey`. I probably need some options set up, but that's the current behaviour.

**Comment by dnknn** [comment]
@ssborbis Thank you for your efforts, I saw the `keyword` UI, But I can't see the startup hotkey of `CS` omnibox. 👇 Are you missing some code?  Therefore cannot be tested.
`chrome://settings/searchEngines#:~:text=Search engines added by extensions`

**Comment by ssborbis** [comment]
omnibox keyword is `cs` i.e. `cs amz smartphone` to search for "smartphone" using an engine with the keyword "amz"

**Comment by dnknn** [comment]
> omnibox keyword is `cs`


<img align=right width=20% src="https://user-images.githubusercontent.com/10995302/105120432-2d70c600-5b0d-11eb-8911-cc6f2d160f0b.png">


No... What I mean is that when I enter `CS` in the browser addressbar, there is no omnibox prompt/show.

[the `manifest.json` file](https://github.com/ssborbis/ContextSearch-web-ext/blob/57dc2be3458a83edcfb87c863aa9f33e52159ea8/src/manifest.json#L123-L125) have this code,  but the strange thing is:  I don’t see `ContextSearch-web-ext` either at `chrome://settings/searchEngines#:~:text=Search engines added by extensions` ....

and [The release version of the Chrome store](https://chrome.google.com/webstore/detail/ddippghibegbgpjcaaijbacfhjjeafjh) does not have this `"keyword": "cs"` code.

Maybe the way I test the download is wrong,  So wait for the store version to be released, I will test it

**Comment by ssborbis** [comment]
I'm using the latest code from the repo in Chromium and things appear to be working correctly. If you need to wait on a release to test, it shouldn't be too long.

**Comment by ssborbis** [comment]
I just submitted to chromestore. Let me know if you get the omnibox working with v1.28

**Comment by dnknn** [comment]
> I just submitted to chromestore. Let me know if you get the omnibox working with v1.28

Hi~ @ssborbis v1.28 is good! 
I can see `chrome:settings/searchEngines#:~:text=ContextSearch` here, so can use `cs` omnibox.

---

- ### 💡 Feature request 1: 
When typing `cs` + 'omnibox-key' in the omnibox address bar, able to display the title of the corresponding search engine in real time, There should be this omnibox API, I remember I used this kind of omn that instantly displays the corresponding entries.
![image](https://user-images.githubusercontent.com/10995302/105585454-aac95e80-5dcb-11eb-848b-89e92207bf1f.png)

If it can be displayed as the corresponding search engine name in real time, the experience will be great!

---

- ### 💡 Feature request 2: 
Should we add a CSS interactive background color to the search engine manager's `li:hover`?

```css
/*It’s just an example, it’s not perfect yet, because the folders are expanded separately*/

#searchEnginesParentContainer li.treeNode:hover	{background:#b23bc614}

```
---

- ### 💡 Feature request 3: 

There is a problem with the expand/collapse icon of the folder, 

When you select it, i.e. `li.treeNode>.selected ` , you can't see its icon at all, because it is pure white and close to the background color.
![image](https://user-images.githubusercontent.com/10995302/105593984-009f0600-5dce-11eb-87f1-fcdc26c4dfcf.png)
Therefore, it should be changed, and it is better to increase the size of the icon to make it easier to see.


---

- ### 💥/🐞 Current bugged behavior: 
Unable to set omnibox-key, I only succeeded once,
the performance is: the save is successful, but the page is restored to empty after `F5` reload,
In the same way, when it is successfully saved, then it cannot be cleared (reset)

![bug](https://user-images.githubusercontent.com/10995302/105588805-95086900-5dcc-11eb-97a7-09f0c4225049.gif)

**Comment by ssborbis** [comment]
> Unable to set omnibox-key, I only succeeded once,
the performance is: the save is successful, but the page is restored to empty after F5 reload,
In the same way, when it is successfully saved, then it cannot be cleared (reset)

Got it fixed. I'll get a patch today.

> Feature request 1:

Ok, now I'm seeing how the omnibox is meant to do suggestions. Code updated

> Feature request 2

I'll try some thigns

> Feature request 3

Done

**Comment by ssborbis** [comment]
v1.28.1 awaiting approval in the chrome store

Looks like you need to add a space after your hotkey list / keyword to get the suggestions

**Comment by dnknn** [comment]
v1.28.1, Yes. Nice fixed!  thankyou very much, and sorry for my English...

- ### 1 
I am not vertically centered here, we need  `top:` ? 

```css
#pageTilesFolderBrowser SPAN, .collapse {top:2px}
```

----

- ## 2
> Looks like you need to add a space after your hotkey list / keyword to get the suggestions

No....  No matter how hard I test and work hard, I still can't program `suggestion`.
`suggestion` means the name of the search-engine, not the name of the extension.


 ⌨(omnibox-key/hotkey) |  **suggestion** |    
:---: |--- |--- |
`cs` | `ContextSearch web-ext`  | that's right!
`cs g ` | `CS -> google` | expected behavior


---
- ## 3
Since you added the omnibox-Key, a good feature has been lost. Can you recover it?

At present, only `cs`+`smartphone` cannot call the last engine to search, this is very inconvenient...

-  3.1 ❥ **Expected/fixed/perfect behavior**: 
　　　　✚. if no enter omniboxkey/hotkey, can use the last time search engine by default.
　　　　✚. For the same reason, it can also show `suggestion` .  i.e.  

` |  No omnibox-key/hotkey |  **suggestion**(Prompt text displayed)  |    
:---:|--- |--- |--- |
Current |  `cs` | `ContextSearch web-ext`  | that's right! but  changed to ↓
Expect  |  `cs` | `CS -> google` | here `google` is the last search engine used

I said before, seeing at 👇
`https://github.com/ssborbis/ContextSearch-web-ext/issues/274#issuecomment-731936056#:~:text=open without,just follow to open as the search engine used last time`

**Comment by ssborbis** [comment]
1. done
2. I'm getting different behaviour in Firefox, where I do my developing. I'll look into it
3. looks like that function got reverted when "fixing" the suggestions. I'll see what can be done.

**Comment by ssborbis** [comment]
I added an advanced option to use the Last Used search engine in the omnibox when no keyword or hotkey is present, otherwise it uses the first search engine in the tree with a hotkey or keyword

**Comment by dnknn** [comment]
> 2\. I'm getting different behaviour in Firefox

I use Chrome/Chromium 86 , Thanks♪(･ω･)ﾉ

**Comment by ssborbis** [comment]
Latest push has this behaviour in chromium.

I have Google as my first engine with a keyword, so it's acting as the default
g = google
a = amazon
e = ebay 

![Peek 2021-01-25 00-07](https://user-images.githubusercontent.com/24310997/105667710-6c05d800-5ea1-11eb-8fec-cff1d164b11e.gif)

**Comment by dnknn** [comment]
Good!  In fact,  Maybe you continue add an advanced option to `the Last Used search engine` ?

Because there are 2 types of `the Last Used search engine`  :

 - Only the Last omnibox Used (limited to omnibox itself)
 - Global the Last  Used  (any Last Used )

In other words, separate `the Last omnibox Used` of omnibox as an advanced option,

This is also a useful option, users can easily separate the `Key` search in the address-bar ⚔ the regular search on the page.

**Comment by ssborbis** [comment]
> Good! In fact, Maybe you continue add an advanced option to the Last Used search engine

Done. Omnibox remembers last used engines(s) and uses them as the default engine(s) when performing a search without a keyword or hotkey

**Comment by dnknn** [comment]
> Done. Omnibox remembers last used engines(s) and uses them as the default engine(s) when performing a search without a keyword or hotkey

@ssborbis Hi~, can you release V1.28.2 to test ?

**Comment by ssborbis** [comment]
why not just load the source as an unpacked extension? 

chrome://extensions/ 
turn on developer mode
load unpacked
browse to source folder containing manifest.json

**Comment by dnknn** [comment]
> why not just load the source as an unpacked extension?

@ssborbis  Yeah, It's perfect now for omnibox! I finally put forward a requirement, then we can close this issue!

- ## can you add an option to omnibox ❓ (omnibox open method)👇

![image](https://user-images.githubusercontent.com/10995302/105898497-79af8f00-6054-11eb-95e7-5bde7205966b.png)
See the picture, you should be able to understand the meaning of the feature!

**Comment by ssborbis** [comment]
> can you add an option to omnibox question (omnibox open method)point_down

I can, but there won't be two separate methods for engines and folders. It will be one setting

**Comment by ssborbis** [comment]
Changes are up. Do yourself a favour and backup your CS config before trying the latest code and keep an eye out for the options page failing. I had a bug in some of the newest code that caused problems. I think it's fixed, but just a heads up.

**Comment by dnknn** [comment]
Thank you very much for your support!
