### ISSUE TITLE
Feature request:  Multi-line selection opens multi-line search

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#472]
Hi✿(◕‿◕)✿!  Only an **example** can describe the feature :)
- There are now 4 lines of text below :
```
Multi-line Keyword1
Multi-line Keyword2
Multi-line Keyword3
Multi-line Keyword4
```

> Obviously, this has 4 lines (`\n`) of text.
`Multi-line Keyword1\nMulti-line Keyword2\nMulti-line Keyword3\nMulti-line Keyword4`

- **Current state** :
	ContextSearch can easily implement a keyword to open multiple search engines, 
	But [a multi-line keyword](https://user-images.githubusercontent.com/10995302/159533500-27943c77-5b8f-480c-b0e5-aea96de0983c.png) cannot use **a search engine** to open the corresponding **multi-line search**.

- **Expected behavior of this feature** :
	1. `getSelection()` [select them all](https://user-images.githubusercontent.com/10995302/159533500-27943c77-5b8f-480c-b0e5-aea96de0983c.png)
	2. Start ContextSearch to search, 4 tabs will be opened at the same time (or delayed in sequence to avoid server refusal to respond)
![2](https://user-images.githubusercontent.com/10995302/159534632-7ff1a634-3420-472a-9126-adf64ceda14a.png)
	3. Done!

-------------------------

- **Summarize**: 
	That is to say, multi-line search mode, which opens multi-tab pages by separating newlines (ie `\n`).
	It may be possible technically, but the question is, how to realize it, and in what way to realize this function :)
	For example, advanced options add a UI switch : 
	* ☑ **Enable multiline search mode**
		* ☑ And enable **sequential delay** (tooltip: 	Prevent access denied when opening multiple pages at once.)
		* **maximum number of lines** (tooltip: To avoid misoperation and open dozens of hundreds of tabs at the same time, When `getSelection()` exceeds the set maximum number of rows, this function is not executed, but a prompt is displayed.)

**Comment by dnknn** [comment]
update edited :)

**Comment by ssborbis** [comment]
There's a hidden option in the release I just dropped ( 1.38 ) called `multilinesAsSeparateSearches`. If you enable that, it will treat multi-lines as separate search terms. Right now, it only works from the context menu, but it's there. I'll get something more robust when I have time.

**Comment by ssborbis** [comment]
Actually, I don't think that change made it to the new release. It is in the repo, however.

**Comment by dnknn** [comment]
@ssborbis Hi, add sub-options of this advanced option, Do you think it is necessary?
> Of course, don't worry, just let you know. :)

- `☑ And enable sequential delay` (tooltip: Prevent access denied when opening multiple pages at once.)


- `maximum number of lines` (tooltip: To avoid misoperation and open dozens of hundreds of tabs at the same time, When getSelection() exceeds the set maximum number of rows, this function is not executed, but a prompt is displayed.)


For example: `userOptions.splitMultilineAmount`

```html
<input type="number" min="5" max="50" step="1" id="splitMultilineAmount">
```

```js
if ( searchTerms.split('\n').length > userOptions.splitMultilineAmount )	{
	
	alert(`Exceeds the set number of lines !`);
	return;
	
}

```

**Comment by ssborbis** [comment]
It won't work in the release ( 1.38 ). It should be working from the code in the development repo, however.

I'll post a beta you can test.

**Comment by ssborbis** [comment]
> Since there is no UI option, I manually enable it in the Console

You can do that or manually edit the preferences JSON from here.
![edit](https://user-images.githubusercontent.com/24310997/163314198-639862fb-caed-4306-9849-2917ae9eaf76.jpg)

**Comment by ssborbis** [comment]
https://github.com/ssborbis/ContextSearch-web-ext/releases/download/v1.39b1/contextsearch_web_ext-1.39b1-an+fx.xpi

**Comment by dnknn** [comment]
@ssborbis Version V1.39 still doesn't work -_-

I use the Chrome browser and [installed the latest version V1.39 on the CWS store.](https://chrome.google.com/webstore/detail/ddippghibegbgpjcaaijbacfhjjeafjh)
then manually edit the preferences JSON, Save, but still doesn't work...
![224_15180703](https://user-images.githubusercontent.com/10995302/163558395-8bfd6732-a584-42ca-90b9-0647b1abc9a7.png)

**Comment by ssborbis** [comment]
Do you have an example webpage where it's not working? I've been using a simple test page and I've tested in textarea fields and with `<br>` tags as newlines and it is working in chromium. 

I did notice the "Cancel" button isn't working if you get prompted for being over the limit. I have that fixed in the repo.

**Comment by dnknn** [comment]
> Do you have an example webpage where it's not working?

🤝ThankS! Now it works! the principle needs to restart the browser to work.

-----

Now I also found another problem:
1) text selection `getSelection()`
2) Then start ContextSearch, the search box is automatically populated with `getSelection()`, right?
3) ContextMenu and QuickMenu are fine.
4) But [the startup of these two places](https://user-images.githubusercontent.com/10995302/163656198-c2b4fd44-502a-4ea8-84aa-0316d2d05270.png) cannot be automatically filled in `getSelection()`.

In fact, this problem is similar to insensitivity. In most cases, it will not be automatically filled, or it needs to be restarted repeatedly to be automatically filled.

I don't know why, or what code you changed, the previous 1.28/1.29 versions were perfect, never had this problem.

**Comment by dnknn** [comment]
> Do you have an example webpage where it's not working?

🤝ThankS! Now it works! the principle needs to restart the browser to work.

-----

@ssborbis  Now I also found **another problem** for the new version:
1) text selection `getSelection()`
2) Then start ContextSearch, the search box is automatically populated with `getSelection()`, right?
3) ContextMenu and QuickMenu are fine. [no problem](https://user-images.githubusercontent.com/10995302/163656735-12272e4a-2d4b-485f-84fa-8ab5682f88db.gif)

4) But [the startup of these two places](https://user-images.githubusercontent.com/10995302/163656198-c2b4fd44-502a-4ea8-84aa-0316d2d05270.png) cannot be automatically filled in `getSelection()`. [Problem/Bug](https://user-images.githubusercontent.com/10995302/163656892-a3fa518d-8619-425f-a74a-e13641742e6b.gif)


In fact, this problem is similar to insensitivity. In most cases, it will not be automatically filled, or it needs to be restarted(click again) repeatedly to be automatically filled.

I don't know why, or what code you changed, the previous 1.28/1.29 versions were perfect, never had this problem.

**Comment by ssborbis** [comment]
Does this problem happen when `multilinesAsSeparateSearches` = false ?

**Comment by dnknn** [comment]
> Does this problem happen when multilinesAsSeparateSearches = false ?

exactly the same, has nothing to do with `multilinesAsSeparateSearches`

**Comment by ssborbis** [comment]
This may be related to the issue of editing the search bar in the qm is not updating the search terms in the actual search.

I have that fixed, and I tested the problem of selected text not populating the toolbar and sidebar menus when they are opened, and it seems to be working normally. 

Updates are in the dev repo, if you're able to test.

**Comment by ssborbis** [comment]
> I tested the problem of selected text not populating the toolbar and sidebar menus when they are opened, and it seems to be working normally.

Correction. It seems to be working only *some* of the time. I'll dig around and try to find why that is.

**Comment by ssborbis** [comment]
Ok, you can try what's in the dev repo to see if it works for you. For some reason I don't understand, chromium-based browsers require a slight delay in setting the search bar value to the search terms, as seen by `getSelection()`. I'm currently using a 10ms delay, and seem to get the correct selected text in the search bar 10/10 times.

**Comment by dnknn** [comment]
> chromium-based browsers require a slight delay in setting the search bar value to the search terms, as seen by `getSelection()`. I'm currently using a 10ms delay, and seem to get the correct selected text in the search bar 10/10 times.


thanks for your hard working!
I tested it and found it to be perfect, and I didn't find the problem of not filling or not updating the filling.

**Comment by ssborbis** [comment]
v1.41.1 is out. I'm not sure this fix made it into a release before now. Let me know if this is working correctly, or just close out the issue, and I'll assume it is.

**Comment by ssborbis** [comment]
How often are you using this feature? I wonder if it wouldn't be useful to make this standard behavior, but prompt with a yes/no confirmation dialog if the search terms are multiline.

**Comment by Chealer** [comment]
@dnknn: Is this issue resolved in version 1.47.15 (or ulterior)?
